# Generated by Django 5.0.2 on 2024-05-02 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_user_alter_event_organizer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ManyToManyField(blank=True, null=True, related_name="events", to=settings.AUTH_USER_MODEL),
        ),
    ]
