# Generated by Django 5.0.2 on 2024-05-02 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_description_alter_event_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ManyToManyField(blank=True, related_name="events", to=settings.AUTH_USER_MODEL),
        ),
    ]
