# Generated by Django 5.0.2 on 2024-05-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"], "verbose_name": "event", "verbose_name_plural": "events"},
        ),
    ]
